apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
## image placeholder for the image name and tag to be replaced by the image name and tag built by the GitHub Actions workflow
images:
  - name: PROJECT/IMAGE
    newName: jakousa/colorcontent