apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/00-namespace.yaml
  - manifests/01-Configmap.yaml
  - manifests/postgres-db.yaml
  - manifests/backend-deployment.yaml
  - manifests/backend-svc.yaml
  - manifests/frontend-deployment.yaml
  - manifests/frontend-svc.yaml
  - manifests/ingress.yaml
  - Jobs/cronjob.yaml
  
  