apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: <your-docker-hub-username>/pingpong:latest # Update with your image tag
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_HOST
              value: "postgres-svc"
            - name: POSTGRES_DB
              value: "pingpong_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
