apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
  namespace: project
spec:
  type: ClusterIP
  ports:
  - port: 2345          # Must match 2345 in ConfigMap & Ingress
    targetPort: 3000    # Flask container port in backend.py
  selector:
    app: todo-backend
