apiVersion: v1
data:
    API_KEY: ENC[AES256_GCM,data:vvMsDRY8dROwZW9faQ2LDLpK0yo0mYFcNKM+wdYCxOrAT1mcqZJiJD4khawqNhXV,iv:zMFfsBC6vflHmRJU7FH51M8UAHC3hlnsOim3btsRmEA=,tag:AErJDWVOsNCMM4CSk/DNHg==,type:str]
kind: Secret
metadata:
    name: pixabay-apikey
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbXpCOUJBajgydVBrdnQ2
            S0tWWDFFY2JkQktXbUhiZkFMQ1FBaHlxN25vCktkWWJ0ZE40dHhERHZXajVzNHpt
            QU44WXFRUWpNSk5rWWFCSGFvT0c2QkEKLS0tIDVUSTAxZXFxMHFnK1haeHhsRjJP
            S2lsV1RPT3ZEcWM5RzRzZ0Q1TUdmMG8KWh9BovKlApyb06bD1Ltxfuht7JlHOKV1
            D3YRPxIkYwhqgT6YvoSa0SEEfQv7YI0ZFeP3saMWDHOgGIpFjXaItA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jrgejkv0lhjqvgx82wudmqxlf7hfg99uvx0pk8wgwwgwmz8sgyaq98ypd0
    encrypted_regex: ^(data)$
    lastmodified: "2026-07-18T06:37:53Z"
    mac: ENC[AES256_GCM,data:2kpiRdWEmkCcwBfE/k28BmjM81MBCHxydV6qxL96oUh51RRzdWWI2gUYqAwd95piyWezTWZFK5O23xAtooT7S/wMyFTNWmVUQE5nZa/kEQcZ8FEOJU5/DmAn3veCnWaPGoMfoqm9fkio5THcNUYbNFemdexS0dSA/4tUmgYxeWY=,iv:JZcPT9iwmnqkLDBJb967P4j6sJMGzvdXJ003hFatQH4=,tag:QzGAPbSHsqHWBODOHXoIPw==,type:str]
    version: 3.13.2
