apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      initContainers:
        # Wait for Postgres port to respond before starting Flask backend
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - "until nc -z postgres-svc 5432; do echo 'Waiting for Postgres...'; sleep 2; done;"
      containers:
        - name: backend
          image: raghvendrashrinet/projects:todo-backend2.8  # Ensure your real username is set
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: todo-app-config
            - secretRef:
                name: postgres-secret
