name: pipeline
on:
    push:
        branches:
        - main 
        - feature/*
        paths:
        - 'Kubernetes/Chapter-4 Cloud/GitHub Actions-Pipeline/**'
# ghcr these permissions are explicilty defined
permissions:
  contents: read
  packages: write
jobs:
   build:
        runs-on: ${{ matrix.operating_system }}
        strategy:
            matrix:
               operating_system: [ ubuntu-latest]
        steps:
        -  name: checkout
           uses:  actions/checkout@v6
        - name: Docker Login
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            #login into github container registry for pushing image to ghcr also
        - name: GHCR Login
          uses: docker/login-action@v3
          with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically provides a built-in cryptographic token called secrets.GITHUB_TOKEN for every workflow run

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
           # context: .
            push: true
            tags: | 
                 ${{vars.DOCKER_USERNAME}}/projects:${{github.sha}}
                # ghcr.io/${{vars.DOCKER_USERNAME}}/projects:${{github.sha}}
